### PR TITLE
Solves #6 , proper formatting of python files to PEP8 format

### PR DESCRIPTION
**Pull request by Kartik2301**
Updated all the python files to meet the PEP8 standards

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
For now, I'll approve the changes as it's only code formatting.
Keep in mind that as we are still working on automated tests, it's better to commit the changes to your branch as well so that I can clone it and review it as a whole.

**Comment by mrsaicharan1** [comment]
I've reverted the changes as the files still do not follow pep8 guidelines entirely. Please check your PR and submit it again. It's better if you fork the repo on your local machine manually rather than changing it on the web interface.
You should use the command `pep8 <filename> ` on your terminal to check this. 
For example, if you run `pep8 app.py` and there is no output, this means you are good to go. Otherwise, make the mentioned changes. If you require any help, comment on this thread.

**Comment by Kartik2301** [comment]
Also please tell me how much time, do I have for this issue now.

**Comment by mrsaicharan1** [comment]
You can check what all lines are leftover which don't follow the pep8 guidelines using the command `pep8 app.py`

**Comment by Kartik2301** [comment]
Sir , I checked it out and also read some documentation regarding PEP8, it
says a line should not contain more than 79 character, but if we try to
distribute the code over more lines, it will certainly disturb the code, I
have solved problems like multiple imports and whitespace, how do I proceed
now.?

**Pull request merged**
